version: '3.9'
services:
  postgres:
    container_name: postgres
    build:
      context: ./postgres
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'db'
      POSTGRES_INITDB_ARGS: '--encoding=UTF8 --locale=C'
      PGDATA: /var/lib/postgresql/data/pgdata
      TZ: 'UTC'
    ports:
      - "5432:5432"
    volumes:
      - ./db/default/data:/var/lib/postgresql/data
      - ./db/default/initdb.d:/docker-entrypoint-initdb.d

  postgres_e2e_test:
    container_name: postgres-e2e-test
    build:
      context: ./postgres
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: 'e2e_test_user'
      POSTGRES_PASSWORD: 'e2e_test_password'
      POSTGRES_DB: 'e2e_test_db'
      POSTGRES_INITDB_ARGS: '--encoding=UTF8 --locale=C'
      PGDATA: /var/lib/postgresql/data/pgdata
      TZ: 'UTC'
    ports:
      - "5433:5432"
    volumes:
      - ./db/e2e_test/data:/var/lib/postgresql/data
      - ./db/e2e_test/initdb.d:/docker-entrypoint-initdb.d
